### ISSUE TITLE
Search box has case-sensitivity issues and no Enter key support

### ISSUE THREAD

**Issue by Kwpolska** [upendra-k14/pip_gui#11]
1. Search box does nothing when Enter is pressed. A sensible behavior is to run the search.
2. The search also seems to be case-sensitive, which is error-prone (certain popular packages have names starting with capital letters). `pip` does not care.
3. `pip search` also searches descriptions.

**Comment by upendra-k14** [comment]
I have recently fixed the issue of Enter key (develop branch). I am figuring out how to return relevant results and make it case-insensitive. For some packages we get a large number of search results like 'django'. But, if I will try to make the search functionality case insensitive : results of both Uppercase results and Lowercase results will come together which will make the search result longer.
