### ISSUE TITLE
Error in installing package

### ISSUE THREAD

**Issue by Mec-iS** [upendra-k14/pip_gui#13]
I tried to install a package, selecting it and clicking on 'Install' and got this:
![install_error](https://cloud.githubusercontent.com/assets/3146196/16710045/472401ca-4622-11e6-88b3-f9ab5d69cf77.png)

Ok, there is a problem. But in the command line I should actually have a log, instead:
![error_console](https://cloud.githubusercontent.com/assets/3146196/16710047/5e706666-4622-11e6-8836-a4263dcd56ae.png)

I tried to install another one and it worked with no log in the command line at all.

**Comment by upendra-k14** [comment]
I think, I can redirect the error to terminal when exception is caught
