### ISSUE TITLE
Add support for both version of Python's tkinter

### ISSUE THREAD

**Issue by tremblerz** [upendra-k14/pip_gui#16]
Actually this problem is due to difference in `tkinter` and `Tkinter` packages available on python3 and python respectively. This [LINK](http://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter) could be helpful for adding support for both.

**Comment by tremblerz** [comment]
When I ran `python -m pip_tkinter` then this error came -
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/__main__.py", line 8, in <module>
    import tkinter as tk
ImportError: No module named tkinter`

But as we can see it happened to work when I used `python3 -m pip_tkinter`

**Comment by upendra-k14** [comment]
Unfortunately, this GUI package is specifically targeted for Python 3.4+. But, it may be considered to be extended to Python2.7.
