### ISSUE TITLE
Maximize button causing problem

### ISSUE THREAD

**Issue by tremblerz** [upendra-k14/pip_gui#17]
Whenever I press maximize button from default state of window this happens -
![problem](https://cloud.githubusercontent.com/assets/10557215/17022174/0edcff00-4f6a-11e6-9f30-a19a5f401e51.png)

And program seems to not working afterwards.

**Comment by upendra-k14** [comment]
Can you please give the terminal output?

**Comment by tremblerz** [comment]
`python3 -m pip_tkinter`
`2016-07-29 17:04:47,197 - __main__ - INFO - Welcome today`
`2016-07-29 17:07:18,153 - __main__ - ERROR - Logging an uncaught exception in tkinter mainloop`
`Traceback (most recent call last):`
`File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/__main__.py", line 143, in __call__
    return self.func(*args)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 585, in callit
    func(*args)
  File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/manage_installed_modules_page.py", line 319, in update_outdated_packages
    results_tuple = pip_list_outdated_command()
  File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/utils.py", line 286, in pip_list_outdated_command
    latest_version = installed_pkg_list[i].split(' - Latest: ')[1].split(' [')[0]
IndexError: list index out of range
`

**Comment by upendra-k14** [comment]
Can you please post output of : pip3 list --outdated.

**Comment by tremblerz** [comment]
> wget (Current: 2.2 Latest: 3.2)
> fudge (Current: 1.0.3 Latest: 1.1.0)
> mutagen (Current: 1.31 Latest: 1.34)
> soundcloud (Current: 0.4.1 Latest: 0.5.0)
> scdl (Current: v1.3.2 Latest: 1.5.2)
> simplejson (Current: 3.8.0 Latest: 3.8.2)
> checkbox-ng (Current: 0.3 Latest: 0.27)
> Could not find any downloads that satisfy the requirement unity-scope-virtualbox
> checkbox-support (Current: 0.2 Latest: 0.26)
> Could not find any downloads that satisfy the requirement unity-scope-musique
> Could not find any downloads that satisfy the requirement devscripts
> Could not find any downloads that satisfy the requirement unity-scope-colourlovers
> Could not find any downloads that satisfy the requirement unity-scope-firefoxbookmarks
> setuptools (Current: 3.3 Latest: 25.1.1)
> pip (Current: 1.5.4 Latest: 8.1.2)
> plainbox (Current: 0.5.3 Latest: 0.29)
> Could not find any downloads that satisfy the requirement unity-scope-zotero
> Could not find any downloads that satisfy the requirement unity-scope-manpages
> pycurl (Current: 7.19.3 Latest: 7.43.0)
> requests (Current: 2.2.1 Latest: 2.10.0)
> feedparser (Current: 5.1.3 Latest: 5.2.1)
> MarkupSafe (Current: 0.18 Latest: 0.23)

**Comment by upendra-k14** [comment]
Ok, I need to add exceptional cases for "Could not find ...". There is error in parsing output of pip3 list --outdated.

**Comment by upendra-k14** [comment]
Which version of pip are you using? The format of your output is totally different than the output format I get in my machine. However, I am going to add the exception clause for "Could not find ... ".

```
alabaster (0.7.8) - Latest: 0.7.9 [wheel]
awscli (1.10.38) - Latest: 1.10.51 [wheel]
boto (2.40.0) - Latest: 2.42.0 [wheel]
botocore (1.4.28) - Latest: 1.4.41 [wheel]
chardet (2.2.1) - Latest: 2.3.0 [sdist]
checkbox-ng (0.26) - Latest: 0.27 [sdist]
checkbox-support (0.25) - Latest: 0.26 [sdist]
colorama (0.3.3) - Latest: 0.3.7 [wheel]
Django (1.9.7) - Latest: 1.9.8 [wheel]
feedparser (5.1.3) - Latest: 5.2.1 [sdist]
html5lib (0.999) - Latest: 0.999999999 [sdist]
httplib2 (0.8) - Latest: 0.9.2 [sdist]
lxml (3.6.0) - Latest: 3.6.1 [sdist]
Mako (0.9.1) - Latest: 1.0.4 [sdist]
plainbox (0.28) - Latest: 0.29 [sdist]
pycurl (7.19.3) - Latest: 7.43.0 [sdist]
python-apt (0.9.3.5ubuntu2) - Latest: 0.7.8 [sdist]
python-debian (0.1.21-nmu2ubuntu2) - Latest: 0.1.28 [sdist]
requests-oauthlib (0.6.1) - Latest: 0.6.2 [wheel]
s3transfer (0.0.1) - Latest: 0.1.0 [wheel]
selenium (2.53.5) - Latest: 2.53.6 [wheel]
setuptools (24.0.3) - Latest: 25.1.1 [wheel]
urllib3 (1.7.1) - Latest: 1.16 [wheel]
```

**Comment by upendra-k14** [comment]
@tremblerz  I think you are using pip version 1.5.4 instead of 8.1.2+. The output format you posted is pip 1.5.4's output. Therefore, program gets stuck in your case.
