### ISSUE TITLE
Implementing some sort of on-screen logging system

### ISSUE THREAD

**Issue by Mec-iS** [upendra-k14/pip_gui#2]
While using the GUI some messages are logged in the command-line where the script is running. Printing these messages in a box could help the user following the workflow.
For example, having a fixed dialog bar on the lower part of the GUI to log messages telling "Fetching packages from PyPi, please wait..." could improve the user experience and avoid user to get lost.

**Comment by upendra-k14** [comment]
Ok, whenever user has to wait due to process, he should be informed that what is happening, otherwise he will feel application is hanged.

**Comment by harshdattani** [comment]
Are we keeping a option to terminate the operation, in case if user wants to end by any means?

**Comment by upendra-k14** [comment]
No, we have not kept an option to terminate process in between. Thanks for reminding. I will add it. But, do you have any idea how to stall a running function in between using some other event.

**Comment by Mec-iS** [comment]
I think is enough for now that the user is informed when the GUI is waiting
for a response to a request to a remote server to avoid the "no feedback"
situation.

Lorenzo Moriondo, from mobile
https://it.linkedin.com/in/lorenzomoriondo
