### ISSUE TITLE
Scrollbar missing

### ISSUE THREAD

**Issue by Mec-iS** [upendra-k14/pip_gui#4]
In the box for package selection the scrollbar on the right is missing.
Is the box meant for multiple selection? If not, only one package should stay selected.

![scrollbar](https://cloud.githubusercontent.com/assets/3146196/16527261/15e5e140-3fb6-11e6-9bac-332e6fddcec5.png)

**Comment by upendra-k14** [comment]
Issue of scrollbar fixed. Both vertical and horizontal scrollbars can be used now

**Comment by upendra-k14** [comment]
And multiple selection is disabled
