### ISSUE TITLE
'Installed' flag not updated after installation

### ISSUE THREAD

**Issue by Mec-iS** [upendra-k14/pip_gui#5]
In the GUI I have installed one package.
The package got installed but still resulted 'not installed'.

![notinstalled](https://cloud.githubusercontent.com/assets/3146196/16527351/a93a5b10-3fb6-11e6-8c67-4a0a8f00f4d6.png)

I switched to the 'Manage packages' view but it wasn't in the list.

The package resulted installed only after re-running the GUI.

**Comment by upendra-k14** [comment]
I will implement a "Refresh" option and automatically refresh the list of packages after installing a new package

**Comment by Mec-iS** [comment]
> I will implement a "Refresh" option and automatically refresh the list of packages after installing a new package
> This would probably make the user experience too slow, it's not advisable to perform a request each time.

It sounds more appropriate to maintain a cache of packages, and update it when a package get installed or uninstalled. Refresh the cache when a new search is hit.
