### ISSUE TITLE
Reporting relevant search results

### ISSUE THREAD

**Issue by upendra-k14** [upendra-k14/pip_gui#6]
Can the order of search results be improved?
For example, when I type Flask, the most relevant search results "Flask" doesn't show up at top in the main search results area.

**Comment by Mec-iS** [comment]
There is no sorting option provided by the standard interface.
It is possible to use the `pipe` on POSIX: http://stackoverflow.com/questions/28644419/how-does-pip-search-sort-results but it doesn't sound good nor advisable.
In my opinion the list should be ordered for popularity (number of downloads), take a look to [this repo](https://github.com/EliotBerriot/lifter) for an example on how to filter iterables.

**Comment by upendra-k14** [comment]
Duplicate of issue #20
