### ISSUE TITLE
Use entry points, run the proper way

### ISSUE THREAD

**Issue by Kwpolska** [upendra-k14/pip_gui#8]
1. You should use entry_points to create an executable.
2. If you have `__main__.py`, you should use:
   
   ```
   python -m pip_tkinter
   ```

More details: https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/

**Comment by upendra-k14** [comment]
Thanks, using entry points makes app easy to use.
